### ISSUE TITLE
can't click Simulate Location in the debug menu

### ISSUE THREAD

**Issue by Schrims** [xhkz/pokemon-go-keyboard#3]
hi,
i build the app for my iphone and launched it - but after i opened that app i can't click any of the "Simulate Location" items.

Can you tell me how to build the app that i can click the "Simulate Location" items?

**Comment by Abeldvlpr** [comment]
To simulate location you must launch the app from Xcode and keep everything running. Do not unplug your phone, do not quit Xcode.

Launching the installed app from the phone doesn't work, it must be launched from Xcode by clicking the play button.

**Comment by Schrims** [comment]
thanks it's now working!
but i have to select the location file everytime i changed the locaton in the browser - it's not refreshing. Is this normal?

**Comment by Abeldvlpr** [comment]
You need to select it the first time from Debug menu, it should work automatically after. Try relaunching the script if it still doesn't work.

**Comment by Schrims** [comment]
After relaunching etc it still doesen't work - the option "Simulate Location" is still checked, but i have to click it to refresh the location in pokemon

**Comment by Abeldvlpr** [comment]
Have you authorized the Terminal in your System Preferences to access accessibility features in Security and Privacy panel ?

**Comment by Schrims** [comment]
Thanks! You are the man!
I changed that and now i'm fine :)
