### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by pawin** [xhkz/pokemon-go-keyboard#4]
I get this message after `[sudo] pip install -r requirements.txt`
`Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-ItX9HK/protobuf-to-dict/`

**Comment by pawin** [comment]
fix by `[sudo] -H pip install --ignore-installed six`
[PokemonGo-Map](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1475)

**Comment by xhkz** [comment]
Thanks for comment the reference.

**Comment by Steev93** [comment]
It seems to be a issue related to protobuf-to-dict, but actually a version conflict of six.

The final solution is to uninstall the six by

```
 pip uninstall six
```

And then run the

```
pip install -r requirements.txt 
```

it will install everything without any errors.
